### ISSUE TITLE
Craft 4 version

### ISSUE THREAD

**Issue by chadcrowell** [kennethormandy/craft-api2pdf#4]
Will API2PDF be ported to C4? If so do you have a timeline? Thanks.

**Comment by edoardobiasini** [comment]
I’m also interested!

**Comment by chadcrowell** [comment]
Still need this please for Craft 4!

**Comment by edoardobiasini** [comment]
Hi! If I run `composer require kennethormandy/craft-api2pdf:^1.0.0-beta.1` I get no matches. would love to test this on Craft 4!

**Comment by kennethormandy** [comment]
This has been resolved for quite a while, but I also tagged a version v4.0.0 without the beta tag.
